name: CI

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - .github/workflows/*
      - src/**
      - test/**

jobs:
  build_and_test:
    name: Build & Test
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/cswm.sln
    - name: Build
      run: dotnet build src/cswm.sln --no-restore
    - name: Test
      run: dotnet test src/cswm.sln --no-build --verbosity normal
