name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  is_build_required:
    name: Check if Build required
    runs-on: ubuntu-latest
    outputs:
      build_required: ${{ steps.filter.outputs.build_required }}
    steps:
    - uses: dorny/paths-filter@v3.0.0
      id: filter
      with:
        filters: |
          build_required:
            - .github/workflows/*
            - src/**
            - test/**
  build_and_test:
    name: Build & Test
    runs-on: windows-latest
    needs: is_build_required
    if: ${{ needs.is_build_required.outputs.build_required == 'true' }}

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore cswm.sln
    - name: Build
      run: dotnet build cswm.sln -c Release --no-restore
    - name: Test
      run: dotnet test cswm.sln -c Release --no-build --verbosity normal --collect:"XPlat Code Coverage"
    - name: Display Test Coverage
      uses: 5monkeys/cobertura-action@v14
      with:
        path: test/**/TestResults/**/*.xml
        skip_covered: false
        minimum_coverage: 0
