name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  is_build_required:
    name: Check if Build required
    runs-on: ubuntu-latest
    outputs:
      build_required: ${{ steps.filter.outputs.build_required }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          build_required:
            - .github/workflows/*
            - src/**
            - test/**
  build_and_test:
    name: Build & Test
    runs-on: windows-latest
    needs: is_build_required
    if: ${{ needs.is_build_required.outputs.build_required == 'true' }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/cswm.sln
    - name: Build
      run: dotnet build src/cswm.sln -c Release --no-restore
    - name: Test
      run: dotnet test src/cswm.sln -c Release --no-build --verbosity normal
