name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  is_build_required:
    name: Check if Build required
    runs-on: ubuntu-latest
    outputs:
      build_required: ${{ steps.filter.outputs.build_required }}
    steps:
    - uses: dorny/paths-filter@v3.0.0
      id: filter
      with:
        filters: |
          build_required:
            - .github/workflows/*
            - src/**
            - test/**
  
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    needs: is_build_required
    if: ${{ needs.is_build_required.outputs.build_required == 'true' }}
    permissions:
      checks: write # Required to publish Test Results
      pull-requests: write # Required to write Code Coverage PR comment

    steps:
    - uses: actions/checkout@v4.1.1

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore cswm.sln

    - name: Build
      run: dotnet build cswm.sln -c Release --no-restore

    - name: Test
      run: dotnet test cswm.sln -c Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger trx

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ${{ github.workspace }}/test/**/TestResults/**/*
        retention-days: 7
    
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2.16.1
      with:
        trx_files: "${{ github.workspace }}/**/*.trx"
    
    - name: Combine Code Coverage Reports
      uses: danielpalme/ReportGenerator-GitHub-Action@5.2.4
      with:
        reports: "test/**/*.cobertura.xml"
        targetdir: "${{ github.workspace }}"
        reporttypes: "Cobertura"
        verbosity: "Info"
        title: "Merged Code Coverage Report"
        tag: "${{ github.run_number }}_${{ github.run_id }}"
        customSettings: ""
        toolpath: "reportgeneratortool"
    
    - name: Upload Combined Coverage XML
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: ${{ github.workspace }}/coverage.cobertura.xml
        retention-days: 7

    - name: Publish Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.cobertura.xml # test/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: false
        indicators: true
        output: both
        thresholds: '50 75'

    - name: Add Code Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        recreate: true
        path: code-coverage-results.md
