name: CD

on:
  push:
    tags:
      - 'v*'

jobs:
  publish_release:
    name: Publish Release
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/cswm.sln
    - name: Publish
      run: dotnet publish src/cswm/cswm.csproj --no-restore -c Release -o cswm
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.7.1
      with:
        type: "zip"
        filename: "cswm.zip"
        path: "cswm"
    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "cswm.zip"
        draft: true
        prerelease: true
        generateReleaseNotes: true
