name: CD

on:
  push:
    tags:
      - 'v*'

jobs:
  publish_release:
    name: Publish Release
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore cswm.sln
    - name: Publish
      run: dotnet publish cswm.App/cswm.App.csproj --no-restore -c Release -o cswm
    - name: Rename Executable
      run: mv cswm/cswm.App.exe cswm/cswm.exe
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.7.1
      with:
        type: "zip"
        filename: "cswm.zip"
        path: "cswm"
    - name: Create Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: "cswm.zip"
        draft: true
        prerelease: true
        generateReleaseNotes: true
